### ISSUE TITLE
Consider adding instructions on f"" strings

### ISSUE THREAD

**Issue by kangwon-naver** [kangwonlee/18pf_lpthw_template#15]
[LPTHW website](https://learnpythonthehardway.org/python3/ex5.html) started using it already

**Comment by kangwonlee** [comment]
``` python
"%s %d" % ('str', 10)
```
works for python2 and python3

Also, C `printf()` uses similar formatting, too.

**Comment by kangwonlee** [comment]
Let's just use `%`s for now
